### PR TITLE
new sync marker and `get_worker_bound` API

### PR DESCRIPTION
**Pull request by alfredodeza**
This adds a new key to the replica log that defaults to `incremental` (as documented) and changes the `get_worker_bound` API so that it can get all the information coming from the result of the request.

Since we are not using everything, and to be as least disruptive as possible, the consumers of this function still retrieve only what they need (e.g. `timestamp` is not always used).

Tests where added for `get_worker_bound`

### CODE REVIEW

**Comment by jdurgin** [comment]
All looks good to me!

**Comment by jdurgin** [comment]
feel free to merge with my Reviewed-by once it passes the teuthology tests

**Comment by alfredodeza** [comment]
thank you @jdurgin !

**Comment by alfredodeza** [comment]
had some success!

    {duration: 3695.5370898246765, flavor: basic, owner: adeza@magna002, success: true}

    2015-01-28 17:24:11,456.456 WARNING:teuthology.report:No job_id found; not reporting results
    2015-01-28 17:24:11,456.456 INFO:teuthology.run:pass

**Pull request merged**
