### PR TITLE
add rgwx-copy-if-newer param to sync_object_intra_region

### PR DESCRIPTION
**Pull request by cbodley**

### CODE REVIEW

**Comment by ktdreyer** [comment]
Does this require a minimum version of Ceph?

**Comment by cbodley** [comment]
@ktdreyer it adds a parameter which would be ignored by unsupported versions. but the feature is being backported to hammer

**Comment by ktdreyer** [comment]
Thanks @cbodley , and for those following along at home, that is http://tracker.ceph.com/issues/16262

**Comment by yehudasa** [comment]
@cbodley need to see that new error returned in case it's not newer is handled correctly

**Comment by cbodley** [comment]
@yehudasa in testing, i saw the destination gateway getting a 304: NOT_MODIFIED reply from the source gateway, and returning a 200: OK response to the sync agent. are there other cases that would return 304 directly to the sync agent?

**Comment by cbodley** [comment]
@yehudasa i have a radosgw-agent branch that includes the 304 handling, but i took it out because it wasn't being exercised. should i pull it back in anyway, to make the agent more tolerant of future changes in the gateway?

**Comment by alfredodeza** [comment]
@cbodley I'm no longer clear if this is good to be merged or if we have to wait for some integration tests. Can you confirm if this is OK to be merged to cut a release (or ping me here when that is the case?)

**Comment by cbodley** [comment]
@alfredodeza To be on the safe side, I added back the handling for 304: not modified, including a unit test in test_worker.py. I tested this manually against a hammer branch that includes https://github.com/ceph/ceph/pull/9671, and verified via radosgw logs that a full sync was not copying objects that were already up to date (though the sync agent was getting a 200: OK response to these requests). I'm confident that it's ready to merge/release.

**Pull request merged**
